#version 460

layout (local_size_x = 16, local_size_y = 16) in;
layout(rgba16f,set = 0, binding = 0) uniform image2D image;

void main() {
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

	ivec2 size = imageSize(image);

    if(texelCoord.y < 300) {
        imageStore(image, texelCoord, vec4(0.1, 0.3, 0.6, 1.0));
    } else {
    imageStore(image, texelCoord, vec4(0.4, 0.4, 0.5, 1.0));
    }
}